// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOIOejyRl0bSOcUYt1STEMPI5MoTPOgc',
    appId: '1:475749652471:web:5977c041426c7c4c0a80f2',
    messagingSenderId: '475749652471',
    projectId: 'crowdpass-app',
    authDomain: 'crowdpass-app.firebaseapp.com',
    storageBucket: 'crowdpass-app.firebasestorage.app',
    measurementId: 'G-JGMPDQJ7Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQT5LigkeHr4w0thB6EkXS1k-ZD-TU5J0',
    appId: '1:475749652471:android:92f254409e7ccd040a80f2',
    messagingSenderId: '475749652471',
    projectId: 'crowdpass-app',
    storageBucket: 'crowdpass-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqUm4ExJvz5PsvKy7X8u7A056ERErTUg',
    appId: '1:475749652471:ios:c9248f7a691b23ef0a80f2',
    messagingSenderId: '475749652471',
    projectId: 'crowdpass-app',
    storageBucket: 'crowdpass-app.firebasestorage.app',
    iosBundleId: 'com.example.crowdpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGqUm4ExJvz5PsvKy7X8u7A056ERErTUg',
    appId: '1:475749652471:ios:c9248f7a691b23ef0a80f2',
    messagingSenderId: '475749652471',
    projectId: 'crowdpass-app',
    storageBucket: 'crowdpass-app.firebasestorage.app',
    iosBundleId: 'com.example.crowdpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAOIOejyRl0bSOcUYt1STEMPI5MoTPOgc',
    appId: '1:475749652471:web:3a65c11ff3e73acf0a80f2',
    messagingSenderId: '475749652471',
    projectId: 'crowdpass-app',
    authDomain: 'crowdpass-app.firebaseapp.com',
    storageBucket: 'crowdpass-app.firebasestorage.app',
    measurementId: 'G-Y2Q3444PHT',
  );

}